### ISSUE TITLE
CD with Heroku and Github Actions

### ISSUE THREAD

**Issue by Ivan753** [kzagorulko/flower-system#51]
Необходимо настроить деплой на хероку с помощью `Github Actions` (был выбран, т.к. используется для `CI`)
для ветки `develop`

В задаче описан один из возможных вариантов с использованием `Docker`

#### Предварительные действия

1. Создать аккаунт на [Heroku](https://heroku.com)
2. Установить [heroku cli](https://devcenter.heroku.com/articles/heroku-cli#download-and-install) (для тестирования)
3. Установить [Docker](https://docs.docker.com/get-docker/) (для тестирования)

### Ход работы

Задачу можно решить в два шага: работа с `Docker` и работа со связкой `Github Actions` и `Heroku`

#### 1. Разработка Dockerfile

Необходимо настроить `Dockerfile` и поместить его в корень проекта (можно в другую директорию, учитывая это в других пунктах).
Может выглядеть примерно так:

```Dockerfile
FROM postgres:latest

# install Python 3
RUN apt-get update && apt-get install -y python3 python3-pip
RUN apt-get -y install python3.7-dev
RUN apt-get install postgresql-server-dev-10 gcc python3-dev musl-dev

# ...

CMD ./scripts/deploy_backend.sh && ./scripts/deploy_frontend.sh
```

Файл скриптов должны содержать команды для сборки бекенда (зависимости, миграции) и фронтенда

В результате должна быть возможность создания `image` и `container`:

```bash
> docker build -t flower-system .
> docker run -d --rm -p 80:3000 --name flower-system flower-system
```

По адресу `127.0.0.1:80` должен быть доступен сайт

#### 2. Проработка Workflow

Релиз на удаленный сервер хероку с локальной машины можно выполнить с помощью следующих команд (в директории с `Dockerfile`, т.е. в корневой):

```bash
> heroku login     # авторизация в heroku
> heroku create flower-system    # или другое название приложения, уникальное - создание приложения из консоли
> heroku container:login      # работа с Dockerfile
> heroku container:push web
> heroku container:release web
```

Автоматическое развертывание выполняется с помощью тех же команд, за исключением авторизации: производится с помощью `HEROKU_API_KEY` - переменную можно поместить в окружение `Settings \ Secret`, как и `HEROKU_APP_NAME `

Таким образом, workflow может выглядеть следующим образом:

```yaml
name: Deploy to Heroku

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
```

Этот `YAML` файл протестирован - рабочая версия; деплой станет работать после релиза на `develop`

### Результат задачи

Результат должен быть следующим:
- получен метод создания образа и контейнера
- создано приложение `heroku`, выполнен тестовый деплой (из консоли) и настроен `workflow`
- оставлены инструкции в `README` (при необходимости)

### Примечание

При желании можно согласовать другое решение
Например, с использованием `Docker Compose` или готового `actions` для сборки

### Полезные ссылки

- [https://dev.to/heroku/deploying-to-heroku-from-github-actions-29ej](https://dev.to/heroku/deploying-to-heroku-from-github-actions-29ej) - Deploying to Heroku from GitHub Actions
- [https://habr.com/ru/company/southbridge/blog/329262/](https://habr.com/ru/company/southbridge/blog/329262/) - Как создать современную CI/CD-цепочку с помощью бесплатных облачных сервисов
- [https://devcenter.heroku.com/articles/container-registry-and-runtime#getting-started](https://devcenter.heroku.com/articles/container-registry-and-runtime#getting-started) - Container Registry & Runtime (Docker Deploys) # Getting Started
- [https://semaphoreci.com/community/tutorials/creating-a-heroku-like-deployment-solution-with-docker](https://semaphoreci.com/community/tutorials/creating-a-heroku-like-deployment-solution-with-docker) - Creating a Heroku-like Deployment Solution with Docker (Использование `Docker Hub` для деплоя на произвольный сервер)
